### ISSUE TITLE
修改values添加探针

### ISSUE THREAD

**Issue by yogiseven** [kubeservice-stack/OpsCenter#15]
问题情况：
在values的prometheusOperator 的二级标签prometheusConfigReloader添加probe配置

具体涉及到的是pod < prometheus-metrics-kube-prometheus-st-prometheus  >里面的container < config-reloader >

通过helm template metrics . --namespace monitoring >> metrics-allinone.yaml  发现生成的yaml文件里面没有probe相关的配置，导致pod无法启动
![图片](https://user-images.githubusercontent.com/37892682/225831280-a7b0b9cc-f838-42fa-b62c-c02180ef1595.png)

![图片](https://user-images.githubusercontent.com/37892682/225830177-44873e5b-5fe5-4af4-a337-a966cb8add6e.png)

期望看到的结果：
1，生成的yaml文件中有probe相关的配置
2，通过yaml文件能正常启动pod

修改的values代码片段：

    ##Create a servicemonitor for the operator

    serviceMonitor:
    ## Scrape interval. If not set, the Prometheus default scrape interval is used.
    ##
    
    interval: ""
    ## Scrape timeout. If not set, the Prometheus default scrape timeout is used.
    scrapeTimeout: ""
    selfMonitor: true
    
    ## Metric relabel configs to apply to samples before ingestion.
    ##
    metricRelabelings: []
    # - action: keep
    #   regex: 'kube_(daemonset|deployment|pod|namespace|node|statefulset).+'
    #   sourceLabels: [__name__]

    #   relabel configs to apply to samples before ingestion.
    ##
    relabelings: []
    # - sourceLabels: [__meta_kubernetes_pod_node_name]
    #   separator: ;
    #   regex: ^(.*)$
    #   targetLabel: nodename
    #   replacement: $1
    #   action: replace

    ## Resource limits & requests
    ##
      resources:
        limits:
          cpu: 500m
          memory: 1002Mi
        requests:
          cpu: 500m
          memory: 1002Mi
      livenessProbe:
        exec:
          command:
          - ls
          - /home/
      readinessProbe:
        exec:
          command:
          - ls
          - /home/

      # Required for use in managed kubernetes clusters (such as AWS EKS) with custom CNI (such as calico),
      # because control-plane managed by AWS cannot communicate with pods' IP CIDR and admission webhooks are not working
      ##
      hostNetwork: false

      ## Define which Nodes the Pods are scheduled on.
      ## ref: https://kubernetes.io/docs/user-guide/node-selection/
      ##
      nodeSelector: {}

      ## Tolerations for use with node taints
      ## ref: https://kubernetes.io/docs/concepts/configuration/taint-and-toleration/
      ##
      tolerations: []
      # - key: "key"
      #   operator: "Equal"
      #   value: "value"
      #   effect: "NoSchedule"

      ## Assign custom affinity rules to the prometheus operator
      ## ref: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/
      ##
      affinity: {}
        # nodeAffinity:
        #   requiredDuringSchedulingIgnoredDuringExecution:
        #     nodeSelectorTerms:
        #     - matchExpressions:
        #       - key: kubernetes.io/e2e-az-name
        #         operator: In
        #         values:
        #         - e2e-az1
        #         - e2e-az2
      dnsConfig: {}
        # nameservers:
        #   - 1.2.3.4
        # searches:
        #   - ns1.svc.cluster-domain.example
        #   - my.dns.search.suffix
        # options:
        #   - name: ndots
        #     value: "2"
      #   - name: edns0
      securityContext:
        fsGroup: 65534
        runAsGroup: 65534
        runAsNonRoot: true
        runAsUser: 65534

      ## Container-specific security context configuration
      ## ref: https://kubernetes.io/docs/tasks/configure-pod-container/security-context/
      ##
      containerSecurityContext:
        allowPrivilegeEscalation: false
        readOnlyRootFilesystem: true

      # Enable vertical pod autoscaler support for prometheus-operator
      verticalPodAutoscaler:
        enabled: false
        # List of resources that the vertical pod autoscaler can control. Defaults to cpu and memory
        controlledResources: []

    # Define the max allowed resources for the pod
    maxAllowed: {}
    # cpu: 200m
    # memory: 100Mi
    # Define the min allowed resources for the pod
    minAllowed: {}
    # cpu: 200m
    # memory: 100Mi

    updatePolicy:
      # Specifies whether recommended updates are applied when a Pod is started and whether recommended updates
      # are applied during the life of a Pod. Possible values are "Off", "Initial", "Recreate", and "Auto".
      updateMode: Auto

      ## Prometheus-operator image
      ##
      image:
        repository: registry.paas/opscenter/prometheus-operator
        tag: v0.60.1
        sha: ""
        pullPolicy: IfNotPresent

      ## Prometheus image to use for prometheuses managed by the operator
      ##
      # prometheusDefaultBaseImage: registry.paas/opscenter/prometheus

      ## Alertmanager image to use for alertmanagers managed by the operator
      ##
      # alertmanagerDefaultBaseImage: registry.paas/opscenter/alertmanager

      ## Prometheus-config-reloader
      ##
      prometheusConfigReloader:
        image:
          repository: registry.paas/opscenter/prometheus-config-reloader
          tag: v0.60.1
          sha: ""

    # resource config for prometheusConfigReloader
    resources:
      limits:
        cpu: 500m
        memory: 505Mi
      requests:
        cpu: 500m
        memory: 505Mi
    livenessProbe:
      exec:
        command:
        - ls
        - /home/
    readinessProbe:
      exec:
        command:
        - ls
        - /home/

      ## Thanos side-car image when configured
      ##
      thanosImage:
        repository: registry.paas/opscenter/thanos
        tag: v0.28.1
        sha: ""

      ## Set a Field Selector to filter watched secrets
      ##

**Comment by dongjiang1989** [comment]
@yogiseven  具体是一个的deployment？

**Comment by yogiseven** [comment]
想通过values给  statefulset :prometheus-metrics-kube-prometheus-st-prometheus的 pods增加限额和探针，限额添加生成正常，探针的添加不符合预期。

**Comment by dongjiang1989** [comment]
@yogiseven  请描述清楚：您在那个标签下添加的配置，导致什么结果，与您的那个预期结果不符合～  请引用代码块

**Comment by dongjiang1989** [comment]
@yogiseven  添加 featrue 在 #17 。可使用 feat-probe 验证

**Comment by yogiseven** [comment]
使用feat-probe分支的代码，重新helm template生成的yaml文件，
目前看pod 【prometheus-metrics-kube-prometheus-st-prometheus 】里面的container 【config-reloader】 依然没有probe相关配置。
