### ISSUE TITLE
enable ipFamilyPolicy

### ISSUE THREAD

**Issue by yogiseven** [kubeservice-stack/OpsCenter#20]
目前没有显式设定 .spec.ipFamilyPolicy ，当创建服务时，Kubernetes 从所配置的第一个 service-cluster-ip-range 种为服务分配一个集群 IP，并设置 .spec.ipFamilyPolicy 为 SingleStack；
希望能把.spec.ipFamilyPolicy 设置为 PreferDualStack，当在双栈集群上创建此服务时，Kubernetes 会为该服务分配 IPv4 和 IPv6 地址。

这样便于双栈集群中部分NoePort的service能同时分配IPV6和IPV4的地址
主要涉及服务：grafana，prometheus，alertmanager。

**Comment by matthewei** [comment]
I will fix it, Please assign it to me @dongjiang1989

**Comment by matthewei** [comment]
Hi, Jian @yogiseven , In my opinion, we can ignore SingleStack and set PreferDualStack instead of it. @dongjiang1989 , shall we do that?

**Comment by dongjiang1989** [comment]
> Hi, Jian @yogiseven , In my opinion, we can ignore SingleStack and set PreferDualStack instead of it. @dongjiang1989 , shall we do that?i

Great! `PreferDualStack` is usefull in some certain scene, but `SingleStack`is the most commonly now.  Setting `SingleStack` as default value in `value.yaml`

**Comment by yogiseven** [comment]
fixed

**Comment by yogiseven** [comment]
enable ipFamilyPolicy success
